[package]
name = "livestack-shared"
version = "0.1.0"
authors = ["Your Name Here"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.0"

[dev-dependencies]
assert_matches = "1.5.0"
