[package]
name = "shared-py"
version = "0.1.0"
authors = ["Your Name Here"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.19.0"
livestack-shared = { path = "../shared" }
